services:
  - type: web
    name: robinson-portfolio-backend
    env: node
    repo: https://github.com/your-username/robinson-portfolio-backend.git
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: robinson-portfolio-backend
          property: port
      - key: DB_HOST
        fromDatabase:
          name: portfolio-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: portfolio-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: portfolio-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: portfolio-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: portfolio-db
          property: password
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ELEVENLABS_API_KEY
        sync: false # Set this manually in Render dashboard
      - key: FRONTEND_URL
        value: https://your-frontend-domain.com
      - key: AUDIO_STORAGE_PATH
        value: /tmp/storage/audio
    healthCheckPath: /api/health
    plan: starter # Change to 'standard' for production

databases:
  - name: portfolio-db
    databaseName: portfolio_db
    user: portfolio_user
    plan: starter # Change to 'standard' for production
